### ISSUE TITLE
Various Windows Compilation Issue - Link _toFloat, _eLut

### ISSUE THREAD

**Issue by chkone** [belcour/alta#1]
Hello,

I meet some compilation issues.
Compiler:
Visual Studio 2013 - x64

I modify my config.py by adding:
MSVC_VERSION   = '12.0'
TARGET_ARCH    = 'x86_64'

And:
OPENEXR_INC    = ['#external/build/include/OpenEXR']
OPENEXR_LIB    = ['Half.lib', 'Iex-2_2.lib', 'IexMath-2_2.lib', 'IlmImf-2_2.lib', 'IlmThread-2_2.lib', 'IlmImfUtil-2_2.lib', 'Imath-2_2.lib']
OPENEXR_DIR    = ['#external/build/lib']

OpenEXR was compiled by myself using the lastest from (same compiler etc...):
https://github.com/openexr/openexr (6f6d9ce)

Eigen 3 was installed and pass all the test but I still have:
Checking for eigen3 using pkg-config... (cached) no
Checking for C++ header file Eigen/Core... (cached) yes
Checking for C++ header file unsupported/Eigen/LevenbergMarquardt... (cached) yes

Why "eigen3 "no""?

For OpenEXR still ok:
Checking for C++ library Half.lib... (cached) yes
Checking for C++ header file ImfStdIO.h... (cached) yes

I want to use brdf_slide but I have linking issues:
scons: done reading SConscript files.
scons: Building targets ...
link /dll /out:build\plugins\data_brdf_slice.dll /implib:build\plugins\data_brdf_slice.lib /LIBPATH:external\b
uild\lib /LIBPATH:build\core Half.lib Iex-2_2.lib IexMath-2_2.lib IlmImf-2_2.lib IlmThread-2_2.lib IlmImfUtil-
2_2.lib Imath-2_2.lib Half.lib core.lib build\sources\plugins\data_io\slice.obj
Microsoft (R) Incremental Linker Version 12.00.31101.0
Copyright (C) Microsoft Corporation.  All rights reserved.

   Creating library build\plugins\data_brdf_slice.lib and object build\plugins\data_brdf_slice.exp
slice.obj : error LNK2001: unresolved external symbol "private: static union half::uif const * const half::_to
Float" (?_toFloat@half@@0QBTuif@1@B)
slice.obj : error LNK2001: unresolved external symbol "private: static unsigned short const * const half::_eLu
t" (?_eLut@half@@0QBGB)
build\plugins\data_brdf_slice.dll : fatal error LNK1120: 2 unresolved externals
scons: *** [build\plugins\data_brdf_slice.dll] Error 1120
scons: building terminated because of errors.

If I check the Mangling name from the dll/lib:
?_eLut@half@@0QBGB
?_toFloat@half@@0QBTuif@1@B

As you can see it is different:
ATLA expect "?_toFloat@half@@0QBTuif@1@B" the compiler generate "?_toFloat@half@@0QBTuif@1@B"
ATLA expect "?_eLut@half@@0QBGB" the compiler generate "?_eLut@half@@0QBGB"

The website (http://alta.gforge.inria.fr/install.html) do not provide the version of OpenEXR for now I'm using 2.2.0.

Did you know how could I by pass those issues.

The rest compile correctly thanks.

Best Regards

Chkone

**Comment by belcour** [comment]
Hi,

There are no MSVC_VERSION and TARGET_ARCH options in the configuration file. You need to specify them in the CXX and CCFLAGS options. Also you should use the same MSVC environment for both ALTA and OpenEXR. That might be the cause of issues.

That might be the source of trouble here.
> Checking for eigen3 using pkg-config... (cached) no
> 

This means that the pkg software (not provided on Windows) was not found or that it was unable to automatically locate eigen3. 

Best,
-Laurent

**Comment by chkone** [comment]
I modify SConstruct:

Like that:
env = Environment(variables = vars, ENV = envVars, MSVC_VERSION='12.0', TARGET_ARCH='x86_64')
From:
http://scons.org/doc/HTML/scons-man.html

Finally I downgrade to "x86" because I wasn't able to find which configuration on  CMake is equivalent to "x86_64", "ia64" ... with Scons.
That work now.

Thanks for your time.

Regards

Chkone

**Comment by belcour** [comment]
Glad that helped. :)

Best,
-Laurent

2017-01-03 22:07 GMT+01:00 chkone <notifications@github.com>:
