### ISSUE TITLE
scons test gives 'downloaded file is inauthentic.'.

### ISSUE THREAD

**Issue by boonta** [belcour/alta#11]
After I built with scons, I tried testing with
`scons tests`

There was an error about downloading file.

> error: downloaded file 'build/tests/gold-metallic-paint.binary' is inauthentic.
> error: got sha256 hash 7df0af666610f38658b54d8a8b32a7cdabdb0aadef37c66c3af9d93e709a4a8f but expected 69c493d7f36fa5267d15948a616056f9bc84e352ec6db49b64afe6ff232e27d6
> scons: *** [build/tests/gold-metallic-paint.binary] build/tests/gold-metallic-paint.binary: downloaded file is inauthentic
> scons: building terminated because of errors.

**Comment by belcour** [comment]
Unfortunately, the MERL database is not accessible on the MIT website anymore. We have contacted the author (so far no answer) and looking for an alternative. So it is expected that this particular test will fail.
