### ISSUE TITLE
brdf2data : failed to load '': No such file or directory

### ISSUE THREAD

**Issue by boonta** [belcour/alta#12]
I tried the tutorial ( http://alta.gforge.inria.fr/tutorial2.html ) and it was a success to generate '.func' file.

but when i tried this ( http://alta.gforge.inria.fr/tools.html )

`brdf2data --input test.func --output test.binary --data data_merl`

It failed.

> ERROR failed to load '': No such file or directory.'

This command also has an error.

`brdf2brdf --input test.func --output test.shader --export explorer`

> INFO parsed input parametrization STARK_2D from name "STARK_2D"
> ERROR not implemented virtual void alta::rational_function_1d::save_body(std::ostream&, const alta::arguments&) const in file sources/core/rational_function.cpp:147
terminate called without an active exception
Aborted

**Comment by boonta** [comment]
It does seem that we have to provide --data-file option in brdf2data as suggested in the code line 77.

`d = plugins_manager::load_data(args["data-file"], args["data"], args);`

However MERL conversion still has a problem.
Since the d_out is not successfully casted in line 122, the code executes another set d_out-set(i,y).

Line 122 is failed.
`if (dynamic_pointer_cast<vertical_segment>(d_out))`

@belcour Could you please check this ?

**Comment by belcour** [comment]
Check branch `fix-data2brdf`. It should fix this issue.
