### ISSUE TITLE
About BRDFGrid

### ISSUE THREAD

**Issue by stephane-lb** [belcour/alta#3]
Bonjour ;-)

First of all, thank you very much, it is a great Swiss army knife for BRDFs ! 

I was playing with it, and I got an issue with BRDFGrid. This is what I did :

```zsh
./softs/data2data --input ./softs/red-fabric.binary --in-data data_merl --output red-fabric.grid --out-data data_grid  

./softs/data2data --input ./red-fabric.grid --in-data data_grid --output red-fabric.exr --out-data data_brdf_slice --param RUSIN_TH_TD_PD --angle 90  
```

That seems normal ( based on the source code ) because you are calling abort() in plugins/data_interpolation/grid.cpp:376

Why are you doing this, is it safe to bypass it ? 

The question is how to convert Alta's BRDF to something else ?

Many thanks,

Stéphane

**Comment by belcour** [comment]
Hi Stephane,

Glad to ear this tools is helping. :)

It seems that the data_grid plugin is broken for the moment and loading `data_grid` files is currently forbidden. You can however load those file as regular `vertical_segments` (without specifying a plugin). However they cannot be interpolated this way (you won't be able to convert them back to `brdf_slice` for example. I will look further into this.

If the goal is to have a way to output ALTA internal format. You will need to use an interpolation scheme. Currently the only one that should be working is the `data_rbf` one. It uses radial basis functions to perform interpolation. However it requires CGAL or flann to build.

Best,
-Laurent

**Comment by stephane-lb** [comment]
Hi,

Just to give a large view of my issue, I have a large 4D array and it would be great if I could import it in Alta to convert it to any other BRDF format. I think the grid format was the easier one, Do you any other recommendation ?

Best,

Stéphane-lb

**Comment by drpaca** [comment]
Dear Stephane,

Could you give us more background on what you try to do?
Is the 4D array an anisotropic BRDF?


Cheers
Romain

**Comment by stephane-lb** [comment]
Bonjour Romain,

I created a BRDFs generator and I would like to transpose them in different formats for comparison, visualisation and analysis. Some of them are isotropic, so the MERL format could be interesting, then others are anisotropic, so I will use another format (ALTA looks nice, not sure I found the spec so : do you have a link ).

Cheers,
Stephane-lb

**Comment by belcour** [comment]
Hi Stephane,

Regarding your problem, the grid format was indeed the easier one to deal with to do conversion from and to other format (brdf_slide or merl). Maybe you can try using the utia (it is a 4D format) data format as a first conversion and then directly map the ALTA internal format to it. Here would be how I would do it:

First convert MERL to UTIA format:
` data2data --input red-fabric.binary --in-data data_merl --output red_fabric.exr --out-data data_utia`

The use a one to one mapping between ALTA and UTIA:
`data2data --input red_fabric.exr --output red_fabric.alta --in-data data_utia`

Do you stuff,

and splat back the value in the ALTA format into UTIA (notice the `--splat` option):
`data2data --input red_fabric.alta --output red_fabric2.exr --out-data data_utia --splat`

Hope that helps,
-Laurent

**Comment by stephane-lb** [comment]
Merci ( Thank you very much for your help )

Best Regards,

Stéphane-lb

**Comment by stephane-lb** [comment]
Hi,

I create this file to test it is a BRDF which is completely white. (rename it in test.alta)
[test.txt](https://github.com/belcour/alta/files/1431790/test.txt)

But then if I do : 

```
./data2data --input ./test.alta --output test.exr --out-data data_utia --splat
./data2data --input ./test.exr --in-data data_utia --output slice.exr --out-data data_brdf_slice --param RUSIN_TH_TD_PD --angle 90
```

I got  the following picture. I can't explain the coloured lines.

I do not think this is normal, and I can not find where is the bug. Do you have any idea ?

<img width="540" alt="screen shot 2017-10-31 at 17 59 28" src="https://user-images.githubusercontent.com/5918598/32240815-3941c732-be66-11e7-884a-e323173064e2.png">

Thanks!

Stéphane-lb

**Comment by belcour** [comment]
Hi Stefan,

I tried on my own and the colours you see appearing are generated during the first conversion. The pattern on the image is due to interpolation+parametrization conversion of those values. Because of a test we added recently, we by default discard invalid angular configuration (incident or outgoing directions below the hemisphere). They weird colours are simply memory location un-written (because of the test).

What you can do is disable this test to ensure that every entry in the utia format is fed. You can do that by adding the `--all-values` argument to the first command:

    ./data2data --input ./test.alta --output test.exr --out-data data_utia --splat

Hopes that helps,
-Laurent

**Comment by stephane-lb** [comment]
That's helping a lot !

Many Thanks!

Stéphane-lb

**Comment by stephane-lb** [comment]
Hi Laurent,

Everything works fine, I think there is one last bug on this picture, there is no reason that I got Cyan pixels. Any idea ?

<img width="521" alt="screen shot 2017-11-09 at 11 18 14" src="https://user-images.githubusercontent.com/5918598/32602928-ead290e6-c53f-11e7-9cfe-4410abd9aeb1.png">

Best Regards,

stephane-lb

**Comment by belcour** [comment]
Hi Stephane,

Nope, there is absolutely no reason to get this artifact. How did you
produced it?

Best,
-Laurent

2017-11-09 12:24 GMT+01:00 Stephane <notifications@github.com>:

**Comment by stephane-lb** [comment]
Simply like this : ( joining the generated.alta )

```
./data2data --input ./generated.alta --output BRDF.exr --out-data data_utia --splat --all-values
./data2data --input ./BRDF.exr --in-data data_utia --output slice-BRDF.exr --out-data data_brdf_slice --param RUSIN_TH_TD_PD --angle 90
```

At the same time, let me add a quick question is there a way in ALTA to integrate the BRDF over the all domain ( to check the Energy Conservative Property ) ? 

Best Regards,
Stéphane-lb

[BRDF.txt](https://github.com/belcour/alta/files/1457862/BRDF.txt)

**Comment by belcour** [comment]
Hi Stephane,

The input file you provided is incorrect for the command you are trying to
perform. It is weird that you did not end up with a SEGGFAULT. Basically
what --splat --all-values does is to take every entry in the first file and
put it into the second file. If the file format is fixed (like data_utia or
data_merl) your input file should have the same number of entries (for utia
it is 82947). But the BRDF.txt you provided has 110k entries.

As for energy conservation, this is in our todo list for the moment. We can
output the integral of the BRDF in a given parametrization, but not
correctly scaled by the projected cosine.

Best,
-Laurent

2017-11-09 15:19 GMT+01:00 Stephane <notifications@github.com>:

**Comment by stephane-lb** [comment]
Thanks Laurent, I fixed it, as you said it was my exporter. Sorry about that.

Best,
stephane-lb
